import Foundation
import Testing

@testable import CherryLily

struct TmuxConfigTests {
  @Test func includesScrollbackLimit() {
    let conf = TmuxConfig.generate(scrollbackLimit: 50_000, userShell: "/bin/zsh")
    #expect(conf.contains("set -g history-limit 50000"))
  }

  @Test func hidesStatusBar() {
    let conf = TmuxConfig.generate(scrollbackLimit: 50_000, userShell: "/bin/zsh")
    #expect(conf.contains("set -g status off"))
  }

  @Test func enablesMouseForScrollback() {
    let conf = TmuxConfig.generate(scrollbackLimit: 50_000, userShell: "/bin/zsh")
    #expect(conf.contains("set -g mouse on"))
  }

  @Test func reliesOnDefaultWheelBindings() {
    let conf = TmuxConfig.generate(scrollbackLimit: 50_000, userShell: "/bin/zsh")
    // We rely on tmux's built-in WheelUpPane/WheelDownPane bindings in the root
    // table (and built-in Escape/q in copy-mode) for wheel-scroll UX. We must NOT
    // unbind those tables, otherwise the user gets stuck in copy-mode after a
    // wheel-up. This test guards against accidentally re-introducing the unbinds.
    #expect(!conf.contains("unbind -a -q -T root"))
    #expect(!conf.contains("unbind -a -q -T copy-mode"))
    #expect(!conf.contains("unbind -a -q -T copy-mode-vi"))
  }

  @Test func unbindsOnlyPrefixTable() {
    let conf = TmuxConfig.generate(scrollbackLimit: 50_000, userShell: "/bin/zsh")
    #expect(conf.contains("unbind -a -q -T prefix"))
  }

  @Test func setsDefaultShell() {
    let conf = TmuxConfig.generate(scrollbackLimit: 50_000, userShell: "/opt/homebrew/bin/fish")
    #expect(conf.contains("set -g default-shell \"/opt/homebrew/bin/fish\""))
  }

  @Test func enablesPassthroughForOSC() {
    let conf = TmuxConfig.generate(scrollbackLimit: 50_000, userShell: "/bin/zsh")
    #expect(conf.contains("set -g allow-passthrough on"))
  }

  @Test func setsXtermTerminal() {
    let conf = TmuxConfig.generate(scrollbackLimit: 50_000, userShell: "/bin/zsh")
    #expect(conf.contains("set -g default-terminal \"xterm-256color\""))
  }

  @Test func keepsSessionsAliveOnDetach() {
    let conf = TmuxConfig.generate(scrollbackLimit: 50_000, userShell: "/bin/zsh")
    #expect(conf.contains("set -g destroy-unattached off"))
  }

  @Test func headerCommentMarksAutoGenerated() {
    let conf = TmuxConfig.generate(scrollbackLimit: 50_000, userShell: "/bin/zsh")
    #expect(conf.hasPrefix("# Auto-generated by CherryLily. Do not edit."))
  }
}
