import Foundation
import Testing

@testable import CherryLily

struct TmuxConfigTests {
  @Test func includesScrollbackLimit() {
    let conf = TmuxConfig.generate(scrollbackLimit: 50_000, userShell: "/bin/zsh")
    #expect(conf.contains("set -g history-limit 50000"))
  }

  @Test func hidesStatusBar() {
    let conf = TmuxConfig.generate(scrollbackLimit: 50_000, userShell: "/bin/zsh")
    #expect(conf.contains("set -g status off"))
  }

  @Test func enablesMouseForScrollback() {
    let conf = TmuxConfig.generate(scrollbackLimit: 50_000, userShell: "/bin/zsh")
    #expect(conf.contains("set -g mouse on"))
  }

  @Test func reEnablesWheelScrollBindings() {
    let conf = TmuxConfig.generate(scrollbackLimit: 50_000, userShell: "/bin/zsh")
    // After `unbind -a`, wheel scroll must be re-bound or the user loses scrollback access.
    #expect(conf.contains("WheelUpPane"))
    #expect(conf.contains("WheelDownPane"))
    #expect(conf.contains("copy-mode -e"))
    // Escape and q must exit copy-mode (re-bound after the unbind block)
    #expect(conf.contains("Escape send-keys -X cancel"))
    #expect(conf.contains("q send-keys -X cancel"))
  }

  @Test func unbindsAllPrefixAndRootKeys() {
    let conf = TmuxConfig.generate(scrollbackLimit: 50_000, userShell: "/bin/zsh")
    #expect(conf.contains("unbind -a -T prefix"))
    #expect(conf.contains("unbind -a -T root"))
  }

  @Test func setsDefaultShell() {
    let conf = TmuxConfig.generate(scrollbackLimit: 50_000, userShell: "/opt/homebrew/bin/fish")
    #expect(conf.contains("set -g default-shell \"/opt/homebrew/bin/fish\""))
  }

  @Test func enablesPassthroughForOSC() {
    let conf = TmuxConfig.generate(scrollbackLimit: 50_000, userShell: "/bin/zsh")
    #expect(conf.contains("set -g allow-passthrough on"))
  }

  @Test func setsXtermTerminal() {
    let conf = TmuxConfig.generate(scrollbackLimit: 50_000, userShell: "/bin/zsh")
    #expect(conf.contains("set -g default-terminal \"xterm-256color\""))
  }

  @Test func keepsSessionsAliveOnDetach() {
    let conf = TmuxConfig.generate(scrollbackLimit: 50_000, userShell: "/bin/zsh")
    #expect(conf.contains("set -g destroy-unattached off"))
  }

  @Test func headerCommentMarksAutoGenerated() {
    let conf = TmuxConfig.generate(scrollbackLimit: 50_000, userShell: "/bin/zsh")
    #expect(conf.hasPrefix("# Auto-generated by CherryLily. Do not edit."))
  }
}
