import Foundation

/// Generates the text of the managed tmux configuration file.
/// Locks down tmux so the user perceives shells as if they were running directly:
/// no status bar, no key bindings, no mouse interception.
nonisolated enum TmuxConfig {
  /// Returns the full text of the managed `tmux.conf` for the given parameters.
  static func generate(scrollbackLimit: Int, userShell: String) -> String {
    """
    # Auto-generated by CherryLily. Do not edit.

    set -g history-limit \(scrollbackLimit)
    set -g status off
    set -g mouse off
    set -g default-terminal "xterm-256color"
    set -g destroy-unattached off
    set -g detach-on-destroy off
    set -g default-shell "\(userShell)"

    # Lock down all keybindings — CherryLily handles all UX
    unbind -a -T prefix
    unbind -a -T root
    unbind -a -T copy-mode
    unbind -a -T copy-mode-vi

    # Tab title / notifications passthrough
    set -g allow-passthrough on
    set -g set-titles on
    set -g set-titles-string "#{pane_title}"
    """
  }
}
