import Foundation

/// Generates the text of the managed tmux configuration file.
/// Locks down tmux so the user perceives shells as if they were running directly:
/// no status bar, no key bindings, no mouse interception except for scroll-wheel
/// access to tmux's own scrollback (Ghostty has no scrollback when tmux owns the pane).
nonisolated enum TmuxConfig {
  /// Returns the full text of the managed `tmux.conf` for the given parameters.
  static func generate(scrollbackLimit: Int, userShell: String) -> String {
    """
    # Auto-generated by CherryLily. Do not edit.

    set -g history-limit \(scrollbackLimit)
    set -g status off
    set -g mouse on
    set -g default-terminal "xterm-256color"
    set -g destroy-unattached off
    set -g detach-on-destroy off
    set -g default-shell "\(userShell)"

    # Disable the prefix table so Ctrl-b shortcuts (new window, split, etc.)
    # don't fire — CherryLily owns those. We intentionally do NOT unbind the
    # `root`, `copy-mode`, or `copy-mode-vi` tables: tmux's defaults for wheel
    # scrolling and copy-mode exit (Escape, q) live there, and unbinding them
    # locks the pane after a wheel-up. `-q` suppresses "table doesn't exist"
    # errors on re-source.
    unbind -a -q -T prefix

    # Mouse drag → enter copy-mode and start a selection. We bind this
    # explicitly (rather than rely on the tmux default) because servers
    # started with an earlier config that did `unbind -a -T root` won't
    # have the default mouse bindings restored on re-source.
    # In alt-screen apps (vim, claude TUI), pass the drag through to the app.
    bind-key -T root MouseDrag1Pane if -Ft= "#{alternate_on}" "send-keys -M" "copy-mode -M"

    # Mouse selection → macOS clipboard via pbcopy. Override the default
    # MouseDragEnd1Pane binding (which relies on OSC 52 → terminal clipboard)
    # to copy directly with pbcopy. More reliable than the OSC 52 path and
    # works regardless of host-terminal OSC 52 support. -X copy-pipe-and-cancel
    # exits copy-mode after copying so the user can keep typing immediately.
    bind-key -T copy-mode    MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel "pbcopy"
    bind-key -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel "pbcopy"

    # Tab title / notifications passthrough
    set -g allow-passthrough on
    set -g set-titles on
    set -g set-titles-string "#{pane_title}"
    """
  }
}
