import Foundation

/// Generates the text of the managed tmux configuration file.
/// Locks down tmux so the user perceives shells as if they were running directly:
/// no status bar, no key bindings, no mouse interception except for scroll-wheel
/// access to tmux's own scrollback (Ghostty has no scrollback when tmux owns the pane).
nonisolated enum TmuxConfig {
  /// Returns the full text of the managed `tmux.conf` for the given parameters.
  static func generate(scrollbackLimit: Int, userShell: String) -> String {
    """
    # Auto-generated by CherryLily. Do not edit.

    set -g history-limit \(scrollbackLimit)
    set -g status off
    # Copy-mode temporarily re-paints the status line at the top of the pane to show
    # the position indicator. Default `status-right` includes the wall-clock time which
    # is meaningless overlay noise — blank it (and `status-left`) so only the position
    # `[<line>/<total>]` shows up.
    set -g status-left ""
    set -g status-right ""
    set -g mouse on
    set -g default-terminal "xterm-256color"
    set -g destroy-unattached off
    set -g detach-on-destroy off
    set -g default-shell "\(userShell)"

    # Load Ghostty's shell integration in the tmux-spawned shell so OSC 133
    # (semantic-prompt) sequences flow through and the worktree spinner fires
    # while commands are running. Without this, integration auto-loads only
    # for shells Ghostty spawns directly, not for shells spawned via tmux.
    # For zsh: point ZDOTDIR at Ghostty's integration dir; its .zshenv chains
    # back to the user's own .zshenv before loading the integration.
    # Bash/fish/elvish: fall through to plain shell — integration deferred.
    set -g default-command '\(defaultCommand)'

    # Disable the prefix table so Ctrl-b shortcuts (new window, split, etc.)
    # don't fire — CherryLily owns those. We intentionally do NOT unbind the
    # `root`, `copy-mode`, or `copy-mode-vi` tables: tmux's defaults for wheel
    # scrolling and copy-mode exit (Escape, q) live there, and unbinding them
    # locks the pane after a wheel-up. `-q` suppresses "table doesn't exist"
    # errors on re-source.
    unbind -a -q -T prefix

    # Mouse drag → enter copy-mode and start a selection. We bind this
    # explicitly (rather than rely on the tmux default) because servers
    # started with an earlier config that did `unbind -a -T root` won't
    # have the default mouse bindings restored on re-source.
    # In alt-screen apps (vim, claude TUI), pass the drag through to the app.
    bind-key -T root MouseDrag1Pane if -Ft= "#{alternate_on}" "send-keys -M" "copy-mode -M"

    # Mouse selection → macOS clipboard via pbcopy. Override the default
    # MouseDragEnd1Pane binding (which relies on OSC 52 → terminal clipboard)
    # to copy directly with pbcopy. More reliable than the OSC 52 path and
    # works regardless of host-terminal OSC 52 support. -X copy-pipe-and-cancel
    # exits copy-mode after copying so the user can keep typing immediately.
    bind-key -T copy-mode    MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel "pbcopy"
    bind-key -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel "pbcopy"

    # Wheel + exit bindings in BOTH copy-mode tables. Defaults exist in copy-mode
    # but not always in copy-mode-vi, and earlier CherryLily configs that did
    # `unbind -a -T copy-mode-vi` leave servers without these defaults — re-source
    # won't restore them. Bind explicitly so trackpad scroll + Escape/q work
    # regardless of $EDITOR-driven mode-keys.
    bind-key -T copy-mode-vi WheelUpPane   send-keys -X scroll-up
    bind-key -T copy-mode-vi WheelDownPane send-keys -X scroll-down
    bind-key -T copy-mode-vi Escape        send-keys -X cancel
    bind-key -T copy-mode-vi q             send-keys -X cancel

    # Tab title / notifications passthrough
    set -g allow-passthrough on
    set -g set-titles on
    set -g set-titles-string "#{pane_title}"

    # Bell forwarding — tmux normally consumes BEL and signals via the status line
    # (which we have off), so it never reaches Ghostty. Configure tmux to pass the
    # bell through so Ghostty's bell handler fires the worktree notification badge
    # and any OSC 9 / OSC 777 desktop notifications also flow through unmodified.
    set -g bell-action any
    set -g visual-bell off
    set -g monitor-bell on
    """
  }

  /// tmux's `default-command` body: if zsh is the user shell AND Ghostty's
  /// shell integration is available, `exec env ZDOTDIR=... zsh -l`; otherwise
  /// `exec $SHELL -l`. Split out so the long shell expression doesn't trip
  /// the line-length lint (single-line in the .conf file regardless).
  private static let defaultCommand: String = [
    #"if [ -n "$GHOSTTY_RESOURCES_DIR" ] && [ -d "$GHOSTTY_RESOURCES_DIR/shell-integration/zsh" ]"#,
    #"&& [ "$(basename "$SHELL")" = "zsh" ]; then"#,
    #"exec env ZDOTDIR="$GHOSTTY_RESOURCES_DIR/shell-integration/zsh" "$SHELL" -l;"#,
    #"else exec "$SHELL" -l; fi"#,
  ].joined(separator: " ")
}
